services:
  apartments:
    environment:
      - NODE_ENV=development
    volumes:
     #- "./logs:/usr/src/app/logs"
      - "logsvol:/usr/src/app/logs"
  mongo:
    command: ['--logpath', '/var/log/mongodb/db.log']
    volumes:
      # - ".data:/data/db"
      # - ".logs:/var/log/mongodb"
      - "datavol:/data/db"
      - "logsvol:/var/log/mongodb"
volumes:
  logsvol:
    external: true
  datavol:
    external: true
