services:
  apartments:
    build: .
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "${PORT:-8081}:8080"
    # volumes:
    #   - "./logs:/usr/src/app/logs"
    environment:
      - NODE_ENV=production
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    # volumes:
    #   - "./data:/data/db"
